import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import LayoutComponents from "../components/layout/layoutComponents";
import SessionProvider from "@/components/SessionProvider";
import QueryProvider from "@/components/QueryProvider";
// const geistSans = Geist({
//   variable: "--font-geist-sans",
//   subsets: ["latin"],
// });

// const geistMono = Geist_Mono({
//   variable: "--font-geist-mono",
//   subsets: ["latin"],
// });

export const metadata: Metadata = {
  title: "hatawgroup",
  description: "Generated by create next app",
};
// ${geistSans.variable} ${geistMono.variable}
export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en" className="name">
      <QueryProvider>
        <SessionProvider>
          <body className={`antialiased main-root`}>
            <LayoutComponents>{children}</LayoutComponents>
          </body>
        </SessionProvider>
      </QueryProvider>
    </html>
  );
}
