import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import LayoutComponents from "../components/layout/layoutComponents";
import SessionProvider from "@/components/SessionProvider";
import QueryProvider from "@/components/QueryProvider";
import { ToastProvider } from "@/components/Dashbord/TostComponents";

export const metadata: Metadata = {
  title: "hatawgroup",
  description: "Generated by create next app",
};
// ${geistSans.variable} ${geistMono.variable}
export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="fa" className={``}>
<meta name="google-site-verification" content="kSg0zTBvoUZ7-muAd8WVhIUfzlQaWUMMRft1bKFLci4" />
      <QueryProvider>
        <ToastProvider>
          <SessionProvider>
            <body className={`antialiased main-root`}>
              <LayoutComponents>{children}</LayoutComponents>
            </body>
          </SessionProvider>
        </ToastProvider>
      </QueryProvider>
    </html>
  );
}
