import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import LayoutComponents from "../components/layout/layoutComponents";
import  SessionProvider  from "@/components/SessionProvider";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en" className="name">
      <SessionProvider>
        <body
          className={`${geistSans.variable} ${geistMono.variable} antialiased main-root`}
        >
          <LayoutComponents>{children}</LayoutComponents>
        </body>
      </SessionProvider>
    </html>
  );
}
