import type { Metadata } from "next";
import "./globals.css";
import LayoutComponents from "@/components/layout/layoutComponents";
import SessionProvider from "@/components/SessionProvider";
import QueryProvider from "@/components/QueryProvider";
import { ToastProvider } from "@/components/Dashbord/TostComponents";
import { NextIntlClientProvider } from "next-intl";
import { getMessages } from "next-intl/server";
import { notFound } from "next/navigation";

export const metadata: Metadata = {
  title: "hatawgroup",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
  params,
}: {
  children: React.ReactNode;
  params: Promise<{ locale: string }>; // در نسخه جدید نکست، پارامترها Promise هستند
}) {
  // 1. دریافت locale از پارامترهای آدرس
  const { locale } = await params;

  // 2. بررسی معتبر بودن زبان (اختیاری اما توصیه شده)
  if (!["en", "ku"].includes(locale)) {
    notFound();
  }

  // 3. دریافت پیام‌های ترجمه برای سمت کلاینت
  const messages = await getMessages();

  // 4. تعیین جهت صفحه (کردی راست‌به‌چپ، انگلیسی چپ‌به‌راست)
  const direction = locale === "ku" ? "rtl" : "ltr";

  return (
    <html lang={locale} dir={direction}>
      <head>
        <meta
          name="google-site-verification"
          content="kSg0zTBvoUZ7-muAd8WVhIUfzlQaWUMMRft1bKFLci4"
        />
      </head>
      <body className="antialiased main-root">
        <NextIntlClientProvider messages={messages} locale={locale}>
          <QueryProvider>
            <ToastProvider>
              <SessionProvider>
                <LayoutComponents>{children}</LayoutComponents>
              </SessionProvider>
            </ToastProvider>
          </QueryProvider>
        </NextIntlClientProvider>
      </body>
    </html>
  );
}